version: '3.3'

networks:
  proxy:
    external: true

services:
  git:
    restart: always
    image: clash_tools:latest
    #ports:
    #  - 1200:1200
    volumes:
      - ./real-configs:/app/configs
    labels:
      - traefik.docker.network=proxy
      - traefik.port=8000
      - "traefik.frontend.rule=Host:xxxx"
      #- traefik.frontend.entryPoints=http
      - traefik.frontend.entryPoints=http,https
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.passHostHeader=true"
    networks:
      - proxy
